/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsInputsRouteImport } from './routes/components/inputs'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsButtonsRouteImport } from './routes/components/buttons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputsRoute = ComponentsInputsRouteImport.update({
  id: '/components/inputs',
  path: '/components/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonsRoute = ComponentsButtonsRouteImport.update({
  id: '/components/buttons',
  path: '/components/buttons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/buttons': typeof ComponentsButtonsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/buttons': typeof ComponentsButtonsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/buttons': typeof ComponentsButtonsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/buttons'
    | '/components/checkbox'
    | '/components/inputs'
    | '/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/buttons'
    | '/components/checkbox'
    | '/components/inputs'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/components/buttons'
    | '/components/checkbox'
    | '/components/inputs'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsButtonsRoute: typeof ComponentsButtonsRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsInputsRoute: typeof ComponentsInputsRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/inputs': {
      id: '/components/inputs'
      path: '/components/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/buttons': {
      id: '/components/buttons'
      path: '/components/buttons'
      fullPath: '/components/buttons'
      preLoaderRoute: typeof ComponentsButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsButtonsRoute: ComponentsButtonsRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsInputsRoute: ComponentsInputsRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
