/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ComponentsIndexImport } from './routes/components/index'
import { Route as ComponentsInputsImport } from './routes/components/inputs'
import { Route as ComponentsCheckboxImport } from './routes/components/checkbox'
import { Route as ComponentsButtonsImport } from './routes/components/buttons'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsIndexRoute = ComponentsIndexImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsInputsRoute = ComponentsInputsImport.update({
  id: '/components/inputs',
  path: '/components/inputs',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsCheckboxRoute = ComponentsCheckboxImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsButtonsRoute = ComponentsButtonsImport.update({
  id: '/components/buttons',
  path: '/components/buttons',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/components/buttons': {
      id: '/components/buttons'
      path: '/components/buttons'
      fullPath: '/components/buttons'
      preLoaderRoute: typeof ComponentsButtonsImport
      parentRoute: typeof rootRoute
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxImport
      parentRoute: typeof rootRoute
    }
    '/components/inputs': {
      id: '/components/inputs'
      path: '/components/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsImport
      parentRoute: typeof rootRoute
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/buttons': typeof ComponentsButtonsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components': typeof ComponentsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/buttons': typeof ComponentsButtonsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components': typeof ComponentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/components/buttons': typeof ComponentsButtonsRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/': typeof ComponentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/buttons'
    | '/components/checkbox'
    | '/components/inputs'
    | '/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/buttons'
    | '/components/checkbox'
    | '/components/inputs'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/components/buttons'
    | '/components/checkbox'
    | '/components/inputs'
    | '/components/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsButtonsRoute: typeof ComponentsButtonsRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsInputsRoute: typeof ComponentsInputsRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsButtonsRoute: ComponentsButtonsRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsInputsRoute: ComponentsInputsRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/components/buttons",
        "/components/checkbox",
        "/components/inputs",
        "/components/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/components/buttons": {
      "filePath": "components/buttons.tsx"
    },
    "/components/checkbox": {
      "filePath": "components/checkbox.tsx"
    },
    "/components/inputs": {
      "filePath": "components/inputs.tsx"
    },
    "/components/": {
      "filePath": "components/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
